name: Block Pull Requests to Main

on:
  pull_request:
    branches:
      - main

jobs:
  block-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source Branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" = "features" ]; then
            echo "Pull Request from 'features' to 'main' is not allowed."
            exit 1
          fi
          echo "Pull Request is allowed."
